# GitHub Pages Configuration
baseurl: "/sebahub"
url: "https://imam206.github.io/sebahub"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/